name: Update GitHub Actions
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 0" # Run every Sunday at midnight

jobs:
  update-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Create temporary GitHub App Token
        id: app
        uses: actions/create-github-app-token@v2.2.1
        with:
          owner: ${{ github.repository_owner }}
          app-id: ${{ vars.HOUSEKEEPING_BOT_APP_ID }}
          private-key: ${{ secrets.HOUSEKEEPING_BOT_PRIVATE_KEY }}

      - name: Update GitHub Actions
        uses: alchemaxinc/update-deps/actions@v1
        with:
          token: ${{ steps.app.outputs.token }}
          auto-merge: "true"
          base-branch: "main"
          prefixes: "actions"
          file-glob: ".github/**/*.yml"
          branch-prefix: "update-actions"
          pr-title: "chore: Update GitHub Actions"
          commit-message: "chore: update github actions"
